### ISSUE TITLE
Availability of pre build releases/binaries

### ISSUE THREAD

**Issue by priyanknarvekar** [ibm-cloud-security/vault-plugin-auth-ibmcloud#2]
The are currently no pre build releases/binaries. The current process requires building the plugins from source. Customers need prebuild releases. Is there a plan to support pre build releases/binaries ?

**Comment by smatzek** [comment]
We have now tagged a release and have binaries built for it. Future releases will have binaries as well:

https://github.com/ibm-cloud-security/vault-plugin-auth-ibmcloud/releases/tag/v0.1.0
