### ISSUE TITLE
Documented build process fails for vault plugin with current golang 1.15

### ISSUE THREAD

**Issue by priyanknarvekar** [ibm-cloud-security/vault-plugin-auth-ibmcloud#3]
It appears that as of golang 1.15, the arch support for `darwin/386` was removed (https://github.com/golang/go/issues/37610)

Documentation does not indicate the golang version it has been tested with.

**We need to document the golang version that the code and build process has been tested with and/or update the build scripts to not build for arch `darwin/386`**

Build Output: 
```
$ make
==> Checking that code complies with gofmt requirements...
==> Removing old directory...
==> Building...
Number of parallel builds: 7

-->      netbsd/386: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->     windows/386: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->    darwin/amd64: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->     linux/arm64: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->   openbsd/amd64: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->   freebsd/amd64: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->     freebsd/386: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->    netbsd/amd64: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->       linux/arm: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->     linux/amd64: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->   windows/amd64: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->     openbsd/386: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->       linux/386: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->      netbsd/arm: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->     freebsd/arm: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->      darwin/386: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud
-->   solaris/amd64: vault-plugin-auth-ibmcloud/cmd/vault-plugin-auth-ibmcloud

1 errors occurred:
--> darwin/386 error: exit status 2
Stderr: cmd/go: unsupported GOOS/GOARCH pair darwin/386

Makefile:10: recipe for target 'bin' failed
make: *** [bin] Error 1
```

**Comment by smatzek** [comment]
In my testing I used Go 1.14.2 and Vault 1.5.0.

The build scripts match what is in the GCP and Azure plugins, which do contain "darwin/386". The build process used to build Vault, which pulls in the plugins and builds them is setting up the arch differently than how it defaults when called by `make`.

I can recreate this problem at Go 1.15.5. To build this with Go 1.15.5, remove "darwin/386" from 
https://github.com/ibm-cloud-security/vault-plugin-auth-ibmcloud/blob/main/scripts/build.sh#L26

**Comment by smatzek** [comment]
Another, simpler workaround is to run `make dev` which will build the binary for your local architecture and will skip all of the others, including the problematic `darwin/386` arch.
