### ISSUE TITLE
Error when enabling the plugin

### ISSUE THREAD

**Issue by chihebeddine** [ibm-cloud-security/vault-plugin-auth-ibmcloud#6]
I am trying to add the IBM secrets plugin to Vault but have an issue enabling it:

vault version: v1.6.1+ent.hsm
plugin version: v0.1.0
the plugin is added successfuly using the vault register command:

`vault plugin register -sha256=${SHA256} secret vault-plugin-auth-ibmcloud`
But when trying to mount the lugin, i receive the following error message:

`vault auth enable -plugin-name="vault-plugin-auth-ibmcloud" -path="ibmcloud" plugin`

```
* Unrecognised remote plugin message:
This usually means that the plugin is either invalid or simply
needs to be recompiled to support the latest protocol.
```

**Comment by smatzek** [comment]
Closing out for the same reasons given in https://github.com/ibm-cloud-security/vault-plugin-secrets-ibmcloud/issues/9
